copy_standards_task:
  description: >
    Copy the contents of the "Standards & Checklists & Guidelines" section of the {url} lesson plan.
  expected_output: >
    A copy of the "Standards & Checklists & Guidelines" section of the {url} lesson plan.
  agent: data_analyst

identify_standards_task:
  description: >
    Identify the state standards located in the "Standards & Checklists & Guidelines" section of the {url} lesson plan.
  expected_output: >
    A list of state standards located in the "Standards & Checklists & Guidelines" section of the {url} lesson plan.
  agent: lesson_plan_analyst

spreadsheet_input_task:
  description: >
    Input the state standards into the correct location in the {spreadsheet_url} spreadsheet.
  expected_output: >
    The state standards are input into the correct location in the {spreadsheet_url} spreadsheet.
  agent: spreadsheet_expert